fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=88]
